const String THROTTLE_LIMIT = "THROTTLE_LIMIT";
const String SERVER_CLIENT_ID = "SERVER_CLIENT_ID";
const String API_GATEWAY_STAGE_IP = "API_GATEWAY_STAGE_IP";
const String LOG_IN_RELATED_METHOD_THROTTLE_LIMIT = "LOG_IN_RELATED_METHOD_THROTTLE_LIMIT";