const String DUPLICATED_NICKNAME = "DUPLICATED_NICKNAME";
const String DUPLICATED_HALL_OF_FAME = "DUPLICATED_HALL_OF_FAME";
const String NO_SUPPORTED_PROJECT_STATE_CHANGE = "NO_SUPPORTED_PROJECT_STATE_CHANGE";
const String TOO_LONG_PROJECT_NAME = "TOO_LONG_PROJECT_NAME";
const String TOO_SHORT_PROJECT_NAME = "TOO_SHORT_PROJECT_NAME";
const String NOT_ALLOWED_CHARACTER = "NOT_ALLOWED_CHARACTER";
const String TODAY_STICKER_ALREADY_GOT = "TODAY_STICKER_ALREADY_GOT";